export const tuning = {
    keyDims: [18.0, 18.0],
    switchCutout: [14.0, 14.0],
    base1U: [19.05, 19.05],
    bezelGap: 1.05,
    bezelCornerFillet: 1.0,
    layerOffsets: {},
    screwTypes:{"m2_simple":      {minBoss:1.5,screwHoleRadius:2.3/2.0,standoffRadius:3.2/2.0},
                "m2_5_hex_standoffs": {minBoss:1.5,screwHoleRadius:2.9/2.0,hexSize:4.5},
                "m3_tallnut":   {minBoss:1.5,screwHoleRadius:3.3/2.0,nutRadius:4.2/2.0}},
    screwSideBuffer: 0,
    keyShape:"square",
    drawCase:true,
    drawBezel:true,
    drawPlate:true,
    drawPCB:true,
    defaultCase: {
        bezelThickness: 12,
        bezelConcavity: 1.0,
        caseCornerFillet: 6,
        screwSideBuffer: 0,
        maxScrewSpan: 150,
        screwBezelBias:0.5,
        forceSymmetrical:true,
        hasUSBPort:false,
        usbPortPos:1.85,
        usbPortCentered:true,
        caseType:"rectangle"
    }
}